name: 0-Build-Infrastructure

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Environment Name PRD/DEV'
        required: true
        default: 'DEV'

permissions:
  id-token: write
  contents: read

jobs:
  Build-Infrastructure:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Check JSON environment file
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
          files: 'IaC/Environments/${{ github.event.inputs.Environment }}.JSON'
          ignore_case: true
          fail: true

    - name: Load JSON environment file into Environment variables
      if: steps.check_files.outputs.files_exists == 'true'
      uses: rgarcia-phi/json-to-variables@v1.1.0
      with:
        filename: 'IaC/Environments/${{ github.event.inputs.Environment }}.JSON'    
        prefix: config
        masked: false

    - name: Set environment variables required to select corresponding GitHub Action secrets
      shell: bash  
      run: |
          # Set environment variables required for authentication
          echo "SPN_CLIENT_ID_NAME=${{ github.event.inputs.Environment }}_SPN_APPLICATION_CLIENT_ID" >> $GITHUB_ENV
          echo "SPN_CLIENT_SECRET=${{ github.event.inputs.Environment }}_SPN_APPLICATION_SECRET" >> $GITHUB_ENV
          echo "AZUREAD_TENANT_ID=${{github.event.inputs.Environment }}_AZUREAD_TENANT_ID" >> $GITHUB_ENV
          echo "SUBSCRIPTION_ID=${{ github.event.inputs.Environment }}_SUBSCRIPTION_ID" >> $GITHUB_ENV

    - name: 'Az CLI login OpenIDConnect'
      if: ${{contains(github.ref, 'main')}}
      uses: azure/login@v2
      with:
        client-id: ${{ secrets[env.SPN_CLIENT_ID_NAME] }}
        tenant-id: ${{ secrets[env.AZUREAD_TENANT_ID] }}
        subscription-id: ${{ secrets[env.SUBSCRIPTION_ID] }}
        enable-AzPSSession: true
       
    - name: 'Azure login SPN'
      if: ${{ ! contains(github.ref, 'main')}}
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets[env.SPN_CLIENT_ID_NAME] }}","clientSecret":"${{ secrets[env.SPN_CLIENT_SECRET] }}","subscriptionId":"${{ secrets[env.SUBSCRIPTION_ID] }}","tenantId":"${{ secrets[env.AZUREAD_TENANT_ID] }}"}'
        enable-AzPSSession: true 

    - name: 'GitHub Runner infrastructure'
      id: DeployContainerRegistry
      uses: Azure/CLI@v2
      with:
        inlineScript: |
          # Perform Bicep deployment at subscription scope
          cd IaC/0-CICDRunner
          # possible to use CIDR for ACA subnet https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-cidr#cidrsubnet
          az deployment sub create --name "Registry-${{ github.run_id }}" --location=${{ env.config_LOCATION }} --template-file runner-environment.bicep --parameters ContainerRegistry_Name=${{ env.config_ACR_NAME }} deployment_location=${{ env.config_LOCATION }} Environment=${{ env.config_ENVIRONMENT }} LogAnalytics_Workspace_RetentionInDays=${{ env.config_LAW_RETENTION_DAYS }} VirtualNetwork_Prefix=${{ env.config_VIRTUALNETWORK_PREFIX }} ACA_DedicatedSubnet_Prefix=${{ env.config_ACA_SUBNET_PREFIX}} Version=${{ env.config_VERSION }}

    - uses: Azure/CLI@v2
      with:
        inlineScript: |
          # Logoff from Azure and clean cache
          az logout
          az cache purge
          az account clear
