name: 1-BuildRunner
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  BuildRunner:
    runs-on: Build-Runner
    steps:
    - name: show informations
      shell: bash
      run: |
            az --version
            terraform --version
            pwsh
