name: DemoHosted
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:      
    - name: show informations2
      shell: bash  
      run: |
            az --version
            terraform --version
            pwsh
            $psversiontable
